In [32]:
## The output should be power of column -1 i.e ex: First column, 2nd row 16 is 2**(5-1) i.e 2**4 == 16. 
# False takes powers in desceingding order. 
import numpy as np

def vanderFunc(x):
    N = len(x)
    arr = np.column_stack([x**(N-1-i) for i in range(N)])
    print(arr)
    
x = np.array([1, 2, 3, 4, 5])
vanderFunc(x)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [33]:
## By using vander function the output is below, which matches with above output. 

x = np.array([1,2,3,4,5])
np.vander(x, increasing=False)

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])